<?php
/**
 * DefaultApi
 * PHP version 7.3
 *
 * @category Class
 * @package  Towa\GebruederWeissSDK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Logistics Order
 *
 * API to create and retrieve logistics orders
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Towa\GebruederWeissSDK\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Towa\GebruederWeissSDK\ApiException;
use Towa\GebruederWeissSDK\Configuration;
use Towa\GebruederWeissSDK\HeaderSelector;
use Towa\GebruederWeissSDK\ObjectSerializer;

/**
 * DefaultApi Class Doc Comment
 *
 * @category Class
 * @package  Towa\GebruederWeissSDK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class DefaultApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null,
        $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation getLogisticsOrderByOrderId
     *
     * by identifying your logistics-order using the orderId in the path, you get the data of the logistics-order
     *
     * @param  string $order_id order_id (required)
     * @param  string $accept_language set the response language, default is en-US - defines the language following the BCP 47 standard https://tools.ietf.org/html/bcp47 (optional)
     *
     * @throws \Towa\GebruederWeissSDK\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Towa\GebruederWeissSDK\Model\LogisticsOrder|\Towa\GebruederWeissSDK\Model\ErrorMessage|\Towa\GebruederWeissSDK\Model\ErrorMessage
     */
    public function getLogisticsOrderByOrderId($order_id, $accept_language = null)
    {
        list($response) = $this->getLogisticsOrderByOrderIdWithHttpInfo($order_id, $accept_language);
        return $response;
    }

    /**
     * Operation getLogisticsOrderByOrderIdWithHttpInfo
     *
     * by identifying your logistics-order using the orderId in the path, you get the data of the logistics-order
     *
     * @param  string $order_id (required)
     * @param  string $accept_language set the response language, default is en-US - defines the language following the BCP 47 standard https://tools.ietf.org/html/bcp47 (optional)
     *
     * @throws \Towa\GebruederWeissSDK\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Towa\GebruederWeissSDK\Model\LogisticsOrder|\Towa\GebruederWeissSDK\Model\ErrorMessage|\Towa\GebruederWeissSDK\Model\ErrorMessage, HTTP status code, HTTP response headers (array of strings)
     */
    public function getLogisticsOrderByOrderIdWithHttpInfo($order_id, $accept_language = null)
    {
        $request = $this->getLogisticsOrderByOrderIdRequest($order_id, $accept_language);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\Towa\GebruederWeissSDK\Model\LogisticsOrder' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Towa\GebruederWeissSDK\Model\LogisticsOrder', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 400:
                    if ('\Towa\GebruederWeissSDK\Model\ErrorMessage' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Towa\GebruederWeissSDK\Model\ErrorMessage', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 401:
                    if ('\Towa\GebruederWeissSDK\Model\ErrorMessage' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Towa\GebruederWeissSDK\Model\ErrorMessage', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\Towa\GebruederWeissSDK\Model\LogisticsOrder';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Towa\GebruederWeissSDK\Model\LogisticsOrder',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Towa\GebruederWeissSDK\Model\ErrorMessage',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Towa\GebruederWeissSDK\Model\ErrorMessage',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getLogisticsOrderByOrderIdAsync
     *
     * by identifying your logistics-order using the orderId in the path, you get the data of the logistics-order
     *
     * @param  string $order_id (required)
     * @param  string $accept_language set the response language, default is en-US - defines the language following the BCP 47 standard https://tools.ietf.org/html/bcp47 (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getLogisticsOrderByOrderIdAsync($order_id, $accept_language = null)
    {
        return $this->getLogisticsOrderByOrderIdAsyncWithHttpInfo($order_id, $accept_language)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getLogisticsOrderByOrderIdAsyncWithHttpInfo
     *
     * by identifying your logistics-order using the orderId in the path, you get the data of the logistics-order
     *
     * @param  string $order_id (required)
     * @param  string $accept_language set the response language, default is en-US - defines the language following the BCP 47 standard https://tools.ietf.org/html/bcp47 (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getLogisticsOrderByOrderIdAsyncWithHttpInfo($order_id, $accept_language = null)
    {
        $returnType = '\Towa\GebruederWeissSDK\Model\LogisticsOrder';
        $request = $this->getLogisticsOrderByOrderIdRequest($order_id, $accept_language);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getLogisticsOrderByOrderId'
     *
     * @param  string $order_id (required)
     * @param  string $accept_language set the response language, default is en-US - defines the language following the BCP 47 standard https://tools.ietf.org/html/bcp47 (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getLogisticsOrderByOrderIdRequest($order_id, $accept_language = null)
    {
        // verify the required parameter 'order_id' is set
        if ($order_id === null || (is_array($order_id) && count($order_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $order_id when calling getLogisticsOrderByOrderId'
            );
        }
        if (strlen($order_id) > 10) {
            throw new \InvalidArgumentException('invalid length for "$order_id" when calling DefaultApi.getLogisticsOrderByOrderId, must be smaller than or equal to 10.');
        }
        if (strlen($order_id) < 10) {
            throw new \InvalidArgumentException('invalid length for "$order_id" when calling DefaultApi.getLogisticsOrderByOrderId, must be bigger than or equal to 10.');
        }
        if (!preg_match("/[0-9A-Z]{10}/", $order_id)) {
            throw new \InvalidArgumentException("invalid value for \"order_id\" when calling DefaultApi.getLogisticsOrderByOrderId, must conform to the pattern /[0-9A-Z]{10}/.");
        }

        if ($accept_language !== null && strlen($accept_language) > 5) {
            throw new \InvalidArgumentException('invalid length for "$accept_language" when calling DefaultApi.getLogisticsOrderByOrderId, must be smaller than or equal to 5.');
        }
        if ($accept_language !== null && !preg_match("/[a-z][a-z]\\-[A-Z][A-Z]/", $accept_language)) {
            throw new \InvalidArgumentException("invalid value for \"accept_language\" when calling DefaultApi.getLogisticsOrderByOrderId, must conform to the pattern /[a-z][a-z]\\-[A-Z][A-Z]/.");
        }


        $resourcePath = '/logistics-order/{orderId}/';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // header params
        if ($accept_language !== null) {
            $headerParams['accept-language'] = ObjectSerializer::toHeaderValue($accept_language);
        }

        // path params
        if ($order_id !== null) {
            $resourcePath = str_replace(
                '{' . 'orderId' . '}',
                ObjectSerializer::toPathValue($order_id),
                $resourcePath
            );
        }


        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\Query::build($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if ($this->config->getAccessToken() !== null) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }
        // this endpoint requires OAuth (access token)
        if ($this->config->getAccessToken() !== null) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\Query::build($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getStatusByOrderId
     *
     * by identifying your logistics-order using the orderId in the path, you get the current status of the logistics-order
     *
     * @param  string $order_id order_id (required)
     * @param  bool $calculate_eta includes the calculation of an ETA if it is a logistics order (optional, default to false)
     * @param  string $accept_language set the response language, default is en-US - defines the language following the BCP 47 standard https://tools.ietf.org/html/bcp47 (optional)
     *
     * @throws \Towa\GebruederWeissSDK\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Towa\GebruederWeissSDK\Model\OrderCurrentStatus|\Towa\GebruederWeissSDK\Model\ErrorMessage|\Towa\GebruederWeissSDK\Model\ErrorMessage
     */
    public function getStatusByOrderId($order_id, $calculate_eta = false, $accept_language = null)
    {
        list($response) = $this->getStatusByOrderIdWithHttpInfo($order_id, $calculate_eta, $accept_language);
        return $response;
    }

    /**
     * Operation getStatusByOrderIdWithHttpInfo
     *
     * by identifying your logistics-order using the orderId in the path, you get the current status of the logistics-order
     *
     * @param  string $order_id (required)
     * @param  bool $calculate_eta includes the calculation of an ETA if it is a logistics order (optional, default to false)
     * @param  string $accept_language set the response language, default is en-US - defines the language following the BCP 47 standard https://tools.ietf.org/html/bcp47 (optional)
     *
     * @throws \Towa\GebruederWeissSDK\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Towa\GebruederWeissSDK\Model\OrderCurrentStatus|\Towa\GebruederWeissSDK\Model\ErrorMessage|\Towa\GebruederWeissSDK\Model\ErrorMessage, HTTP status code, HTTP response headers (array of strings)
     */
    public function getStatusByOrderIdWithHttpInfo($order_id, $calculate_eta = false, $accept_language = null)
    {
        $request = $this->getStatusByOrderIdRequest($order_id, $calculate_eta, $accept_language);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\Towa\GebruederWeissSDK\Model\OrderCurrentStatus' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Towa\GebruederWeissSDK\Model\OrderCurrentStatus', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 400:
                    if ('\Towa\GebruederWeissSDK\Model\ErrorMessage' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Towa\GebruederWeissSDK\Model\ErrorMessage', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 401:
                    if ('\Towa\GebruederWeissSDK\Model\ErrorMessage' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Towa\GebruederWeissSDK\Model\ErrorMessage', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\Towa\GebruederWeissSDK\Model\OrderCurrentStatus';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Towa\GebruederWeissSDK\Model\OrderCurrentStatus',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Towa\GebruederWeissSDK\Model\ErrorMessage',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Towa\GebruederWeissSDK\Model\ErrorMessage',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getStatusByOrderIdAsync
     *
     * by identifying your logistics-order using the orderId in the path, you get the current status of the logistics-order
     *
     * @param  string $order_id (required)
     * @param  bool $calculate_eta includes the calculation of an ETA if it is a logistics order (optional, default to false)
     * @param  string $accept_language set the response language, default is en-US - defines the language following the BCP 47 standard https://tools.ietf.org/html/bcp47 (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getStatusByOrderIdAsync($order_id, $calculate_eta = false, $accept_language = null)
    {
        return $this->getStatusByOrderIdAsyncWithHttpInfo($order_id, $calculate_eta, $accept_language)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getStatusByOrderIdAsyncWithHttpInfo
     *
     * by identifying your logistics-order using the orderId in the path, you get the current status of the logistics-order
     *
     * @param  string $order_id (required)
     * @param  bool $calculate_eta includes the calculation of an ETA if it is a logistics order (optional, default to false)
     * @param  string $accept_language set the response language, default is en-US - defines the language following the BCP 47 standard https://tools.ietf.org/html/bcp47 (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getStatusByOrderIdAsyncWithHttpInfo($order_id, $calculate_eta = false, $accept_language = null)
    {
        $returnType = '\Towa\GebruederWeissSDK\Model\OrderCurrentStatus';
        $request = $this->getStatusByOrderIdRequest($order_id, $calculate_eta, $accept_language);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getStatusByOrderId'
     *
     * @param  string $order_id (required)
     * @param  bool $calculate_eta includes the calculation of an ETA if it is a logistics order (optional, default to false)
     * @param  string $accept_language set the response language, default is en-US - defines the language following the BCP 47 standard https://tools.ietf.org/html/bcp47 (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getStatusByOrderIdRequest($order_id, $calculate_eta = false, $accept_language = null)
    {
        // verify the required parameter 'order_id' is set
        if ($order_id === null || (is_array($order_id) && count($order_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $order_id when calling getStatusByOrderId'
            );
        }
        if (strlen($order_id) > 10) {
            throw new \InvalidArgumentException('invalid length for "$order_id" when calling DefaultApi.getStatusByOrderId, must be smaller than or equal to 10.');
        }
        if (strlen($order_id) < 10) {
            throw new \InvalidArgumentException('invalid length for "$order_id" when calling DefaultApi.getStatusByOrderId, must be bigger than or equal to 10.');
        }
        if (!preg_match("/[0-9A-Z]{10}/", $order_id)) {
            throw new \InvalidArgumentException("invalid value for \"order_id\" when calling DefaultApi.getStatusByOrderId, must conform to the pattern /[0-9A-Z]{10}/.");
        }

        if ($accept_language !== null && strlen($accept_language) > 5) {
            throw new \InvalidArgumentException('invalid length for "$accept_language" when calling DefaultApi.getStatusByOrderId, must be smaller than or equal to 5.');
        }
        if ($accept_language !== null && !preg_match("/[a-z][a-z]\\-[A-Z][A-Z]/", $accept_language)) {
            throw new \InvalidArgumentException("invalid value for \"accept_language\" when calling DefaultApi.getStatusByOrderId, must conform to the pattern /[a-z][a-z]\\-[A-Z][A-Z]/.");
        }


        $resourcePath = '/logistics-order/{orderId}/current-status';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($calculate_eta !== null) {
            if('form' === 'form' && is_array($calculate_eta)) {
                foreach($calculate_eta as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['calculateETA'] = $calculate_eta;
            }
        }

        // header params
        if ($accept_language !== null) {
            $headerParams['accept-language'] = ObjectSerializer::toHeaderValue($accept_language);
        }

        // path params
        if ($order_id !== null) {
            $resourcePath = str_replace(
                '{' . 'orderId' . '}',
                ObjectSerializer::toPathValue($order_id),
                $resourcePath
            );
        }


        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\Query::build($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if ($this->config->getAccessToken() !== null) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }
        // this endpoint requires OAuth (access token)
        if ($this->config->getAccessToken() !== null) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\Query::build($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation logisticsOrderPost
     *
     * create a logisticsOrder
     *
     * @param  string $accept_language set the response language, default is en-US - defines the language following the BCP 47 standard https://tools.ietf.org/html/bcp47 (optional)
     * @param  \Towa\GebruederWeissSDK\Model\InlineObject $inline_object inline_object (optional)
     *
     * @throws \Towa\GebruederWeissSDK\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return object|\Towa\GebruederWeissSDK\Model\ErrorMessage|\Towa\GebruederWeissSDK\Model\ErrorMessage|\Towa\GebruederWeissSDK\Model\ErrorMessage
     */
    public function logisticsOrderPost($accept_language = null, $inline_object = null)
    {
        list($response) = $this->logisticsOrderPostWithHttpInfo($accept_language, $inline_object);
        return $response;
    }

    /**
     * Operation logisticsOrderPostWithHttpInfo
     *
     * create a logisticsOrder
     *
     * @param  string $accept_language set the response language, default is en-US - defines the language following the BCP 47 standard https://tools.ietf.org/html/bcp47 (optional)
     * @param  \Towa\GebruederWeissSDK\Model\InlineObject $inline_object (optional)
     *
     * @throws \Towa\GebruederWeissSDK\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of object|\Towa\GebruederWeissSDK\Model\ErrorMessage|\Towa\GebruederWeissSDK\Model\ErrorMessage|\Towa\GebruederWeissSDK\Model\ErrorMessage, HTTP status code, HTTP response headers (array of strings)
     */
    public function logisticsOrderPostWithHttpInfo($accept_language = null, $inline_object = null)
    {
        $request = $this->logisticsOrderPostRequest($accept_language, $inline_object);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 202:
                    if ('object' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, 'object', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 400:
                    if ('\Towa\GebruederWeissSDK\Model\ErrorMessage' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Towa\GebruederWeissSDK\Model\ErrorMessage', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 401:
                    if ('\Towa\GebruederWeissSDK\Model\ErrorMessage' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Towa\GebruederWeissSDK\Model\ErrorMessage', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 409:
                    if ('\Towa\GebruederWeissSDK\Model\ErrorMessage' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Towa\GebruederWeissSDK\Model\ErrorMessage', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = 'object';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 202:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        'object',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Towa\GebruederWeissSDK\Model\ErrorMessage',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Towa\GebruederWeissSDK\Model\ErrorMessage',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 409:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Towa\GebruederWeissSDK\Model\ErrorMessage',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation logisticsOrderPostAsync
     *
     * create a logisticsOrder
     *
     * @param  string $accept_language set the response language, default is en-US - defines the language following the BCP 47 standard https://tools.ietf.org/html/bcp47 (optional)
     * @param  \Towa\GebruederWeissSDK\Model\InlineObject $inline_object (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function logisticsOrderPostAsync($accept_language = null, $inline_object = null)
    {
        return $this->logisticsOrderPostAsyncWithHttpInfo($accept_language, $inline_object)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation logisticsOrderPostAsyncWithHttpInfo
     *
     * create a logisticsOrder
     *
     * @param  string $accept_language set the response language, default is en-US - defines the language following the BCP 47 standard https://tools.ietf.org/html/bcp47 (optional)
     * @param  \Towa\GebruederWeissSDK\Model\InlineObject $inline_object (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function logisticsOrderPostAsyncWithHttpInfo($accept_language = null, $inline_object = null)
    {
        $returnType = 'object';
        $request = $this->logisticsOrderPostRequest($accept_language, $inline_object);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'logisticsOrderPost'
     *
     * @param  string $accept_language set the response language, default is en-US - defines the language following the BCP 47 standard https://tools.ietf.org/html/bcp47 (optional)
     * @param  \Towa\GebruederWeissSDK\Model\InlineObject $inline_object (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function logisticsOrderPostRequest($accept_language = null, $inline_object = null)
    {
        if ($accept_language !== null && strlen($accept_language) > 5) {
            throw new \InvalidArgumentException('invalid length for "$accept_language" when calling DefaultApi.logisticsOrderPost, must be smaller than or equal to 5.');
        }
        if ($accept_language !== null && !preg_match("/[a-z][a-z]\\-[A-Z][A-Z]/", $accept_language)) {
            throw new \InvalidArgumentException("invalid value for \"accept_language\" when calling DefaultApi.logisticsOrderPost, must conform to the pattern /[a-z][a-z]\\-[A-Z][A-Z]/.");
        }


        $resourcePath = '/logistics-order';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // header params
        if ($accept_language !== null) {
            $headerParams['accept-language'] = ObjectSerializer::toHeaderValue($accept_language);
        }



        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($inline_object)) {
            if ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($inline_object));
            } else {
                $httpBody = $inline_object;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\Query::build($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if ($this->config->getAccessToken() !== null) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }
        // this endpoint requires OAuth (access token)
        if ($this->config->getAccessToken() !== null) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\Query::build($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
