<?php
/**
 * OrderType
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Logistics Order
 *
 * API to create and retrieve logistics orders
 *
 * OpenAPI spec version: 1.0.0
 * Contact: michael.beck@gw-world.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.25
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;
use \Swagger\Client\ObjectSerializer;

/**
 * OrderType Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class OrderType
{
    /**
     * Possible values of this enum
     */
    const INBOUNDDELIVERY = 'inbounddelivery';
const INBOUNDELIVERYCONFIRMATION = 'inboundeliveryconfirmation';
const OUTBOUNDDELIVERY = 'outbounddelivery';
const OUTBOUNDDELIVERYCONFIRMATION = 'outbounddeliveryconfirmation';
const INBOUNDORDER = 'inboundorder';
const INBOUNDORDERCONFIRMATION = 'inboundorderconfirmation';
const OUTBOUNDORDER = 'outboundorder';
const OUTBOUNDORDERCONFIRMATION = 'outboundorderconfirmation';
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::INBOUNDDELIVERY,
self::INBOUNDELIVERYCONFIRMATION,
self::OUTBOUNDDELIVERY,
self::OUTBOUNDDELIVERYCONFIRMATION,
self::INBOUNDORDER,
self::INBOUNDORDERCONFIRMATION,
self::OUTBOUNDORDER,
self::OUTBOUNDORDERCONFIRMATION,        ];
    }
}
