<?php
/**
 * MyGWStatusCode
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  Towa\GebruederWeissSDK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Logistics Order
 *
 * API to create and retrieve logistics orders
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: michael.beck@gw-world.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.2.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Towa\GebruederWeissSDK\Model;
use \Towa\GebruederWeissSDK\ObjectSerializer;

/**
 * MyGWStatusCode Class Doc Comment
 *
 * @category Class
 * @description status as in myGW shown
 * @package  Towa\GebruederWeissSDK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class MyGWStatusCode
{
    /**
     * Possible values of this enum
     */
    const OPEN = 'Open';
    const IN_PROGRESS = 'InProgress';
    const ATTENTION = 'Attention';
    const CRITICAL = 'Critical';
    const COMPLETED = 'Completed';
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::OPEN,
            self::IN_PROGRESS,
            self::ATTENTION,
            self::CRITICAL,
            self::COMPLETED,
        ];
    }
}


