<?php
/**
 * OrderCurrentStatus
 *
 * PHP version 7.3
 *
 * @category Class
 * @package  Towa\GebruederWeissSDK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Logistics Order
 *
 * API to create and retrieve logistics orders
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.2.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Towa\GebruederWeissSDK\Model;

use \ArrayAccess;
use \Towa\GebruederWeissSDK\ObjectSerializer;

/**
 * OrderCurrentStatus Class Doc Comment
 *
 * @category Class
 * @description contains a referenced order with the actual status and (if feasible) the estimated time of arrival
 * @package  Towa\GebruederWeissSDK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<TKey, TValue>
 * @template TKey int|null
 * @template TValue mixed|null
 */
class OrderCurrentStatus implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'OrderCurrentStatus';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'eta_info' => '\Towa\GebruederWeissSDK\Model\EtaInfo',
        'status_current' => '\Towa\GebruederWeissSDK\Model\Event',
        'order_referenced' => '\Towa\GebruederWeissSDK\Model\OrderReferenced'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'eta_info' => null,
        'status_current' => null,
        'order_referenced' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'eta_info' => 'etaInfo',
        'status_current' => 'statusCurrent',
        'order_referenced' => 'orderReferenced'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'eta_info' => 'setEtaInfo',
        'status_current' => 'setStatusCurrent',
        'order_referenced' => 'setOrderReferenced'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'eta_info' => 'getEtaInfo',
        'status_current' => 'getStatusCurrent',
        'order_referenced' => 'getOrderReferenced'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['eta_info'] = $data['eta_info'] ?? null;
        $this->container['status_current'] = $data['status_current'] ?? null;
        $this->container['order_referenced'] = $data['order_referenced'] ?? null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets eta_info
     *
     * @return \Towa\GebruederWeissSDK\Model\EtaInfo|null
     */
    public function getEtaInfo()
    {
        return $this->container['eta_info'];
    }

    /**
     * Sets eta_info
     *
     * @param \Towa\GebruederWeissSDK\Model\EtaInfo|null $eta_info eta_info
     *
     * @return self
     */
    public function setEtaInfo($eta_info)
    {
        $this->container['eta_info'] = $eta_info;

        return $this;
    }

    /**
     * Gets status_current
     *
     * @return \Towa\GebruederWeissSDK\Model\Event|null
     */
    public function getStatusCurrent()
    {
        return $this->container['status_current'];
    }

    /**
     * Sets status_current
     *
     * @param \Towa\GebruederWeissSDK\Model\Event|null $status_current status_current
     *
     * @return self
     */
    public function setStatusCurrent($status_current)
    {
        $this->container['status_current'] = $status_current;

        return $this;
    }

    /**
     * Gets order_referenced
     *
     * @return \Towa\GebruederWeissSDK\Model\OrderReferenced|null
     */
    public function getOrderReferenced()
    {
        return $this->container['order_referenced'];
    }

    /**
     * Sets order_referenced
     *
     * @param \Towa\GebruederWeissSDK\Model\OrderReferenced|null $order_referenced order_referenced
     *
     * @return self
     */
    public function setOrderReferenced($order_referenced)
    {
        $this->container['order_referenced'] = $order_referenced;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


