<?php
/**
 * AdditionalServiceTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Logistics Order
 *
 * API to create and retrieve logistics orders
 *
 * OpenAPI spec version: 1.0.0
 * Contact: michael.beck@gw-world.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.25
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * AdditionalServiceTest Class Doc Comment
 *
 * @category    Class
 * @description contains information of an additional service. The availability of an additional service depends on the GW product, in combination with the relation and your contract with GW.
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class AdditionalServiceTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "AdditionalService"
     */
    public function testAdditionalService()
    {
    }

    /**
     * Test attribute "additional_service"
     */
    public function testPropertyAdditionalService()
    {
    }

    /**
     * Test attribute "additional_service_text"
     */
    public function testPropertyAdditionalServiceText()
    {
    }

    /**
     * Test attribute "additional_service_attribute"
     */
    public function testPropertyAdditionalServiceAttribute()
    {
    }
}
