<?php
/**
 * ArticleTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Logistics Order
 *
 * API to create and retrieve logistics orders
 *
 * OpenAPI spec version: 1.0.0
 * Contact: michael.beck@gw-world.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.25
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * ArticleTest Class Doc Comment
 *
 * @category    Class
 * @description Article
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ArticleTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Article"
     */
    public function testArticle()
    {
    }

    /**
     * Test attribute "line_item_number"
     */
    public function testPropertyLineItemNumber()
    {
    }

    /**
     * Test attribute "article_id"
     */
    public function testPropertyArticleId()
    {
    }

    /**
     * Test attribute "variant"
     */
    public function testPropertyVariant()
    {
    }

    /**
     * Test attribute "gtin"
     */
    public function testPropertyGtin()
    {
    }

    /**
     * Test attribute "quantity"
     */
    public function testPropertyQuantity()
    {
    }

    /**
     * Test attribute "article_description"
     */
    public function testPropertyArticleDescription()
    {
    }

    /**
     * Test attribute "external"
     */
    public function testPropertyExternal()
    {
    }

    /**
     * Test attribute "measurement"
     */
    public function testPropertyMeasurement()
    {
    }

    /**
     * Test attribute "reference"
     */
    public function testPropertyReference()
    {
    }

    /**
     * Test attribute "logisticsrequirement"
     */
    public function testPropertyLogisticsrequirement()
    {
    }
}
