<?php
/**
 * LogisticsProductTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Logistics Order
 *
 * API to create and retrieve logistics orders
 *
 * OpenAPI spec version: 1.0.0
 * Contact: michael.beck@gw-world.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.25
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * LogisticsProductTest Class Doc Comment
 *
 * @category    Class
 * @description specification of the required GW transport product
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class LogisticsProductTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "LogisticsProduct"
     */
    public function testLogisticsProduct()
    {
    }

    /**
     * Test attribute "product"
     */
    public function testPropertyProduct()
    {
    }

    /**
     * Test attribute "product_service_level"
     */
    public function testPropertyProductServiceLevel()
    {
    }

    /**
     * Test attribute "cargo_type"
     */
    public function testPropertyCargoType()
    {
    }

    /**
     * Test attribute "product_service_level_text"
     */
    public function testPropertyProductServiceLevelText()
    {
    }

    /**
     * Test attribute "additional_services"
     */
    public function testPropertyAdditionalServices()
    {
    }
}
