<?php
/**
 * OrderCurrentStatusTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Logistics Order
 *
 * API to create and retrieve logistics orders
 *
 * OpenAPI spec version: 1.0.0
 * Contact: michael.beck@gw-world.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.25
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * OrderCurrentStatusTest Class Doc Comment
 *
 * @category    Class
 * @description contains a referenced order with the actual status and (if feasible) the estimated time of arrival
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class OrderCurrentStatusTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "OrderCurrentStatus"
     */
    public function testOrderCurrentStatus()
    {
    }

    /**
     * Test attribute "order_referenced"
     */
    public function testPropertyOrderReferenced()
    {
    }

    /**
     * Test attribute "status_current"
     */
    public function testPropertyStatusCurrent()
    {
    }

    /**
     * Test attribute "eta_info"
     */
    public function testPropertyEtaInfo()
    {
    }
}
