<?php
/**
 * EtaInfoTest
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  Towa\GebruederWeissSDK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Logistics Order
 *
 * API to create and retrieve logistics orders
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: michael.beck@gw-world.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.2.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Towa\GebruederWeissSDK\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * EtaInfoTest Class Doc Comment
 *
 * @category    Class
 * @description describes a time window for the estimated time of arrival
 * @package     Towa\GebruederWeissSDK
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class EtaInfoTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "EtaInfo"
     */
    public function testEtaInfo()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "eta_specification"
     */
    public function testPropertyEtaSpecification()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "estimated_time_of_arrival_min"
     */
    public function testPropertyEstimatedTimeOfArrivalMin()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "estimated_time_of_arrival_max"
     */
    public function testPropertyEstimatedTimeOfArrivalMax()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
