<?php
/**
 * EventCallbackTest
 *
 * PHP version 7.3
 *
 * @category Class
 * @package  Towa\GebruederWeissSDK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Logistics Order
 *
 * API to create and retrieve logistics orders
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.2.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Towa\GebruederWeissSDK\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * EventCallbackTest Class Doc Comment
 *
 * @category    Class
 * @description status object, collecting status and translation information
 * @package     Towa\GebruederWeissSDK
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class EventCallbackTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "EventCallback"
     */
    public function testEventCallback()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "event_code"
     */
    public function testPropertyEventCode()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "event_meta_code"
     */
    public function testPropertyEventMetaCode()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "event_reason_code"
     */
    public function testPropertyEventReasonCode()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "event_description"
     */
    public function testPropertyEventDescription()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "event_reason"
     */
    public function testPropertyEventReason()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
