<?php
/**
 * LogisticsOrderCallbacksTest
 *
 * PHP version 7.3
 *
 * @category Class
 * @package  Towa\GebruederWeissSDK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Logistics Order
 *
 * API to create and retrieve logistics orders
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.2.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Towa\GebruederWeissSDK\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * LogisticsOrderCallbacksTest Class Doc Comment
 *
 * @category    Class
 * @description set of callback URL for asynchronous event respones with different purpose
 * @package     Towa\GebruederWeissSDK
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class LogisticsOrderCallbacksTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "LogisticsOrderCallbacks"
     */
    public function testLogisticsOrderCallbacks()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "success_callback"
     */
    public function testPropertySuccessCallback()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "fullfilled_callback"
     */
    public function testPropertyFullfilledCallback()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
