<?php
/**
 * PackageTypeTest
 *
 * PHP version 7.3
 *
 * @category Class
 * @package  Towa\GebruederWeissSDK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Logistics Order
 *
 * API to create and retrieve logistics orders
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.2.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Towa\GebruederWeissSDK\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * PackageTypeTest Class Doc Comment
 *
 * @category    Class
 * @description the package type is following the UN/ECE recommmondation 21, using 2 character codes. See https://www.unece.org/fileadmin/DAM/cefact/recommendations/rec21/rec21rev4_ecetrd309.pdf
 * @package     Towa\GebruederWeissSDK
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class PackageTypeTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "PackageType"
     */
    public function testPackageType()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
