<?php
/**
 * DefaultApiTest
 * PHP version 7.3
 *
 * @category Class
 * @package  Towa\GebruederWeissSDK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Logistics Order
 *
 * API to create and retrieve logistics orders
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.2.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Towa\GebruederWeissSDK\Test\Api;

use \Towa\GebruederWeissSDK\Configuration;
use \Towa\GebruederWeissSDK\ApiException;
use \Towa\GebruederWeissSDK\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * DefaultApiTest Class Doc Comment
 *
 * @category Class
 * @package  Towa\GebruederWeissSDK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class DefaultApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for getLogisticsOrderByOrderId
     *
     * by identifying your logistics-order using the orderId in the path, you get the data of the logistics-order.
     *
     */
    public function testGetLogisticsOrderByOrderId()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getStatusByOrderId
     *
     * by identifying your logistics-order using the orderId in the path, you get the current status of the logistics-order.
     *
     */
    public function testGetStatusByOrderId()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for logisticsOrderPost
     *
     * create a logisticsOrder.
     *
     */
    public function testLogisticsOrderPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
