<?php
/**
 * ReadApiTest
 * PHP version 7.2
 *
 * @category Class
 * @package  TowaGebruederWeissSDK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Logistics Order
 *
 * API to create and retrieve logistics orders
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: michael.beck@gw-world.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.2.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace TowaGebruederWeissSDK\Test\Api;

use \TowaGebruederWeissSDK\Configuration;
use \TowaGebruederWeissSDK\ApiException;
use \TowaGebruederWeissSDK\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * ReadApiTest Class Doc Comment
 *
 * @category Class
 * @package  TowaGebruederWeissSDK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ReadApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for getLogisticsOrderByOrderId
     *
     * by identifying your logistics-order using the orderId in the path, you get the data of the logistics-order.
     *
     */
    public function testGetLogisticsOrderByOrderId()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getStatusByOrderId
     *
     * by identifying your logistics-order using the orderId in the path, you get the current status of the logistics-order.
     *
     */
    public function testGetStatusByOrderId()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
