name: CI

on:
  push:
    branches: [ develop, master ]
  pull_request:
    branches: [ develop ]
  workflow_dispatch:

jobs:
  linting:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'

      - name: Install Composer Dependencies
        run: composer install

      - name: Execute PHPCS
        run: vendor/bin/php-cs-fixer fix --dry-run --allow-risky=yes
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php_version: ["7.3", "7.4"]

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php_version }}

      - name: Install Composer Dependencies
        run: composer install

      - name: Execute PHPUnit
        run: vendor/bin/phpunit
